baseURL: http://example.org/
languageCode: en-us
title: Paul Gessinger
theme: nord
pygmentsUseClasses: yes
params:
  subtitle: Physics, Web Development, Photography
  social:
    - name: "Github"
      icon: "fa-github-alt"
      url: "https://github.com/paulgessinger"
    - name: "Twitter"
      icon: "fa-twitter"
      url: "https://twitter.com/paulgessinger"
    - name: "Instagram"
      icon: "fa-instagram"
      url: "https://www.instagram.com/paulgessinger/"
    - name: "LinkedIn"
      icon: "fa-linkedin-in"
      url: "https://www.linkedin.com/in/paul-gessinger-1b2387b2/"
    - name: "Xing"
      icon: "fa-xing"
      url: "https://www.xing.com/profile/Paul_Gessinger"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true


menu:
  main:
    - name: About
      url: /about
    - name: All Posts
      url: /posts
  footer:
    - name: Imprint
      url: /imprint

