baseURL: https://paulgessinger.com/
languageCode: en-us
title: Paul Gessinger
theme: nord
pygmentsUseClasses: yes
params:
  subtitle: Physics, Web Development, Photography
  social:
    - name: "Git&zwnj;hub"
      icon: "fab gh-icon"
      url: "https://github.com/paulgessinger"
    - name: "T&zwnj;witter"
      icon: "fab tw-icon"
      url: "https://twitter.com/paulgessinger"
    - name: "Inst&zwnj;agram"
      icon: "fab ig-icon"
      url: "https://www.instagram.com/paulgessinger/"
    - name: "Lin&zwnj;kedIn"
      icon: "fab li-icon"
      url: "https://www.linkedin.com/in/paul-gessinger-1b2387b2/"
    - name: "X&zwnj;ing"
      icon: "fab xi-icon"
      url: "https://www.xing.com/profile/Paul_Gessinger"
    - name: "E-Mail"
      icon: "far fa-envelope"
      url: "mailto:hello@paulgessinger.com"

permalinks:
  posts: posts/:year/:slug

enableEmoji: yes

markup:
  goldmark:
    renderer:
      unsafe: yes

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true


menu:
  main:
    - name: About
      url: /about
    - name: All Posts
      url: /posts
  footer:
    - name: Imprint
      url: /imprint

