# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Nord"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.37.0"

assetDir = "assets"

[author]
  name = "Paul Gessinger"
  homepage = "https://paulgessinger.com"
