name: website deploy

on:
  push:
    branches:
      - master
    

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.61.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        ACTIONS_DEPLOY_TARGET: ${{ secrets.ACTIONS_DEPLOY_TARGET }}
        ACTIONS_DEPLOY_PORT: ${{ secrets.ACTIONS_DEPLOY_PORT }}
      run: echo "$ACTIONS_DEPLOY_KEY" > deploy && chmod 400 deploy && rsync -ruv --delete -e "ssh -i deploy -oStrictHostKeyChecking=no -p$ACTIONS_DEPLOY_PORT" public/ $ACTIONS_DEPLOY_TARGET

